// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v5.29.6
// source: cmd/protoc-gen-go/protofif/protofif.proto

package protofif

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	Loc           string                 `protobuf:"bytes,3,opt,name=loc,proto3" json:"loc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_cmd_protoc_gen_go_protofif_protofif_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_protofif_protofif_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_protofif_protofif_proto_rawDescGZIP(), []int{0}
}

func (x *Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Timestamp) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

func (x *Timestamp) GetLoc() string {
	if x != nil {
		return x.Loc
	}
	return ""
}

type Duration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nanoseconds   int64                  `protobuf:"varint,1,opt,name=nanoseconds,proto3" json:"nanoseconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duration) Reset() {
	*x = Duration{}
	mi := &file_cmd_protoc_gen_go_protofif_protofif_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duration) ProtoMessage() {}

func (x *Duration) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_protoc_gen_go_protofif_protofif_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duration.ProtoReflect.Descriptor instead.
func (*Duration) Descriptor() ([]byte, []int) {
	return file_cmd_protoc_gen_go_protofif_protofif_proto_rawDescGZIP(), []int{1}
}

func (x *Duration) GetNanoseconds() int64 {
	if x != nil {
		return x.Nanoseconds
	}
	return 0
}

var file_cmd_protoc_gen_go_protofif_protofif_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         65001,
		Name:          "protofif.bsontags",
		Tag:           "varint,65001,opt,name=bsontags",
		Filename:      "cmd/protoc-gen-go/protofif/protofif.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         65002,
		Name:          "protofif.non_editable",
		Tag:           "varint,65002,opt,name=non_editable",
		Filename:      "cmd/protoc-gen-go/protofif/protofif.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         65003,
		Name:          "protofif.database_default",
		Tag:           "varint,65003,opt,name=database_default",
		Filename:      "cmd/protoc-gen-go/protofif/protofif.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         65004,
		Name:          "protofif.yamltags",
		Tag:           "varint,65004,opt,name=yamltags",
		Filename:      "cmd/protoc-gen-go/protofif/protofif.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         65001,
		Name:          "protofif.json",
		Tag:           "bytes,65001,opt,name=json",
		Filename:      "cmd/protoc-gen-go/protofif/protofif.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         65002,
		Name:          "protofif.moretags",
		Tag:           "bytes,65002,opt,name=moretags",
		Filename:      "cmd/protoc-gen-go/protofif/protofif.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         65003,
		Name:          "protofif.embed",
		Tag:           "varint,65003,opt,name=embed",
		Filename:      "cmd/protoc-gen-go/protofif/protofif.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// Defaults tag bson:"<jsonname>,omitempty" on all go struct fields
	//
	// optional bool bsontags = 65001;
	E_Bsontags = &file_cmd_protoc_gen_go_protofif_protofif_proto_extTypes[0]
	// Defaults tag editable:"false" on all go struct fields
	//
	// optional bool non_editable = 65002;
	E_NonEditable = &file_cmd_protoc_gen_go_protofif_protofif_proto_extTypes[1]
	// Defaults tag database:"default" on all go struct fields
	//
	// optional bool database_default = 65003;
	E_DatabaseDefault = &file_cmd_protoc_gen_go_protofif_protofif_proto_extTypes[2]
	// Defaults tag yaml:"<jsonname>,omitempty" on all go struct fields
	//
	// optional bool yamltags = 65004;
	E_Yamltags = &file_cmd_protoc_gen_go_protofif_protofif_proto_extTypes[3]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string json = 65001;
	E_Json = &file_cmd_protoc_gen_go_protofif_protofif_proto_extTypes[4]
	// optional string moretags = 65002;
	E_Moretags = &file_cmd_protoc_gen_go_protofif_protofif_proto_extTypes[5]
	// optional bool embed = 65003;
	E_Embed = &file_cmd_protoc_gen_go_protofif_protofif_proto_extTypes[6]
)

var File_cmd_protoc_gen_go_protofif_protofif_proto protoreflect.FileDescriptor

const file_cmd_protoc_gen_go_protofif_protofif_proto_rawDesc = "" +
	"\n" +
	")cmd/protoc-gen-go/protofif/protofif.proto\x12\bprotofif\x1a google/protobuf/descriptor.proto\"M\n" +
	"\tTimestamp\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\x12\x10\n" +
	"\x03loc\x18\x03 \x01(\tR\x03loc\",\n" +
	"\bDuration\x12 \n" +
	"\vnanoseconds\x18\x01 \x01(\x03R\vnanoseconds:@\n" +
	"\bbsontags\x12\x1f.google.protobuf.MessageOptions\x18\xe9\xfb\x03 \x01(\bR\bbsontags\x88\x01\x01:G\n" +
	"\fnon_editable\x12\x1f.google.protobuf.MessageOptions\x18\xea\xfb\x03 \x01(\bR\vnonEditable\x88\x01\x01:O\n" +
	"\x10database_default\x12\x1f.google.protobuf.MessageOptions\x18\xeb\xfb\x03 \x01(\bR\x0fdatabaseDefault\x88\x01\x01:@\n" +
	"\byamltags\x12\x1f.google.protobuf.MessageOptions\x18\xec\xfb\x03 \x01(\bR\byamltags\x88\x01\x01:6\n" +
	"\x04json\x12\x1d.google.protobuf.FieldOptions\x18\xe9\xfb\x03 \x01(\tR\x04json\x88\x01\x01:>\n" +
	"\bmoretags\x12\x1d.google.protobuf.FieldOptions\x18\xea\xfb\x03 \x01(\tR\bmoretags\x88\x01\x01:8\n" +
	"\x05embed\x12\x1d.google.protobuf.FieldOptions\x18\xeb\xfb\x03 \x01(\bR\x05embed\x88\x01\x01B7Z5google.golang.org/protobuf/cmd/protoc-gen-go/protofifb\x06proto3"

var (
	file_cmd_protoc_gen_go_protofif_protofif_proto_rawDescOnce sync.Once
	file_cmd_protoc_gen_go_protofif_protofif_proto_rawDescData []byte
)

func file_cmd_protoc_gen_go_protofif_protofif_proto_rawDescGZIP() []byte {
	file_cmd_protoc_gen_go_protofif_protofif_proto_rawDescOnce.Do(func() {
		file_cmd_protoc_gen_go_protofif_protofif_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_go_protofif_protofif_proto_rawDesc), len(file_cmd_protoc_gen_go_protofif_protofif_proto_rawDesc)))
	})
	return file_cmd_protoc_gen_go_protofif_protofif_proto_rawDescData
}

var file_cmd_protoc_gen_go_protofif_protofif_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmd_protoc_gen_go_protofif_protofif_proto_goTypes = []any{
	(*Timestamp)(nil),                   // 0: protofif.Timestamp
	(*Duration)(nil),                    // 1: protofif.Duration
	(*descriptorpb.MessageOptions)(nil), // 2: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
}
var file_cmd_protoc_gen_go_protofif_protofif_proto_depIdxs = []int32{
	2, // 0: protofif.bsontags:extendee -> google.protobuf.MessageOptions
	2, // 1: protofif.non_editable:extendee -> google.protobuf.MessageOptions
	2, // 2: protofif.database_default:extendee -> google.protobuf.MessageOptions
	2, // 3: protofif.yamltags:extendee -> google.protobuf.MessageOptions
	3, // 4: protofif.json:extendee -> google.protobuf.FieldOptions
	3, // 5: protofif.moretags:extendee -> google.protobuf.FieldOptions
	3, // 6: protofif.embed:extendee -> google.protobuf.FieldOptions
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	0, // [0:7] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cmd_protoc_gen_go_protofif_protofif_proto_init() }
func file_cmd_protoc_gen_go_protofif_protofif_proto_init() {
	if File_cmd_protoc_gen_go_protofif_protofif_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_protoc_gen_go_protofif_protofif_proto_rawDesc), len(file_cmd_protoc_gen_go_protofif_protofif_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 7,
			NumServices:   0,
		},
		GoTypes:           file_cmd_protoc_gen_go_protofif_protofif_proto_goTypes,
		DependencyIndexes: file_cmd_protoc_gen_go_protofif_protofif_proto_depIdxs,
		MessageInfos:      file_cmd_protoc_gen_go_protofif_protofif_proto_msgTypes,
		ExtensionInfos:    file_cmd_protoc_gen_go_protofif_protofif_proto_extTypes,
	}.Build()
	File_cmd_protoc_gen_go_protofif_protofif_proto = out.File
	file_cmd_protoc_gen_go_protofif_protofif_proto_goTypes = nil
	file_cmd_protoc_gen_go_protofif_protofif_proto_depIdxs = nil
}
